accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', LoginView.as_view(template_name='accounts/login_form.html',
                                     authentication_form=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(next_page=settings.LOGIN_URL), name='logout'),
    path('profile/', views.profile, name='profile'),

]

blog/urls.py
from django.urls import path, re_path
from . import views, views_cbv

app_name = 'blog'  # 프로젝트 레벨에서 namesapce 지정 후 app_name 지정 필요함
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new, name='post_new'),
    path('<int:id>/edit/', views.post_edit, name='post_edit'),

    path('cbv/', views_cbv.post_list),
    path('cbv/new/', views_cbv.post_new),
    path('cbv/<int:pk>/edit/', views_cbv.post_edit),
    path('cbv/<int:pk>/delete/', views_cbv.post_delete),
]

practice1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import redirect

# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    path('', lambda r:redirect('blog:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('dojo/', include('dojo.urls', namespace='dojo')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('shop/', include('shop.urls', namespace='shop')),
    #namespace 지정 후 각각의 urls.py에서 app_name도 지정해주어야 함
    #name이 중복되는 경우를 대비해 namespace가 필요함
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: #html 페이지에 body 태그를 써야 함
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

practice1/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}AskDjango{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/flatly/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">AskDjango</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-flex justify-content-between" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url "root" %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Content</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            {% if not user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "accounts:signup" %}">회원가입</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "accounts:login" %}?next={{ request.path }}">로그인</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url "accounts:profile" %}">프로필</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url "accounts:logout" %}?next={{ request.path }}">로그아웃</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

{% if messages %}
<div class="container mt-3">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        [{{ message.tags }}]
        {{ message.message }}
    </div>
    {% endfor %}
</div>
{% endif %}

{% block content %}
{% endblock %}

<hr>

<div id="page-footer">
    <div class="container">
        <p class="text-muted">
            &copy; AskDjango
            여러분의 파이썬/장고 페이스 메이커가 되어 드리겠습니다.
        </p>
    </div>
</div>

</body>
</html>