blog/urls.py
from django.urls import path, re_path
from . import views, views_cbv

app_name = 'blog'  # 프로젝트 레벨에서 namesapce 지정 후 app_name 지정 필요함
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:id>/', views.post_detail, name='post_detail'),
    path('new/', views.post_new, name='post_new'),
    path('<int:id>/edit/', views.post_edit, name='post_edit'),

    path('cbv/', views_cbv.post_list),
    path('cbv/new/', views_cbv.post_new),
    path('cbv/<int:pk>/edit/', views_cbv.post_edit),
    path('cbv/<int:pk>/delete/', views_cbv.post_delete),
]

practice1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.shortcuts import redirect

# def root(request):
#     return redirect('blog:post_list')

urlpatterns = [
    path('', lambda r:redirect('blog:post_list'), name='root'),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('dojo/', include('dojo.urls', namespace='dojo')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('shop/', include('shop.urls', namespace='shop')),
    #namespace 지정 후 각각의 urls.py에서 app_name도 지정해주어야 함
    #name이 중복되는 경우를 대비해 namespace가 필요함
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG: #html 페이지에 body 태그를 써야 함
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

blog/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings
from django.urls import reverse
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail

# Create your models here.

def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')

class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, verbose_name='제목',
        help_text='포스팅 제목을 입력해주세요. 최대 100자 내외.') #길이 제한 있는 문자열
    content = models.TextField(verbose_name='내용') #길이 제한 없는 문자열

    photo = ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d',
                                processors=[Thumbnail(300, 300)],
                                format='JPEG',
                                options={'quality': 60}) #업로드 파일을 디렉토리별 시간대별로 관리함

    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50, blank=True, help_text='경도/위도 포맷으로 입력',
        validators=[lnglat_validator],
        )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True) #같은 app내에 있는 클래스를 지정할때 클래스가 뒤에서 지정되어도 ''으로 지정가능
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id'] #'-'붙이면 내림차순 정렬(최근 것부터 보여줌)

    def __str__(self):   #title이 제목값으로 보여지도록 처리함
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.id])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) #Post가 삭제되면 연결된 다수의 post를 모두 삭제해주겠다.
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):    #Tag set에서 name이 보여지도록 하기 위함
        return self.name

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

blog/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from . models import Post
from .forms import PostForm
from django.contrib import messages

# Create your views here.

def post_list(request):
    qs = Post.objects.all()

    q = request.GET.get('q', '') #q가 있으면 가져오고 없으면 빈 문자열
    if q:
        qs = qs.filter(title__icontains=q)

    return render(request, 'blog/post_list.html',{
        'post_list':qs
    })

def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(Post, id=id)  #지정 Record가 없는 것은 서버오류(500)가 아니므로 404오류로 바꿔줘야 한다.

    return render(request, 'blog/post_detail.html', {
        'post':post,
    })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES) #PostForm에서 모델을 Post로 지정해주었기 때문에 form은 PostForm의 인스턴스이자 Post의 인스턴스?
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post) #Post 모델에 get_absolute_url 함수를 정의했으므로 인스턴스를 넣어주기만 해도 url을 추적할 수 있다
    else:                         #따라서 post_detail에 쉽게 접근 가능
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })

def post_edit(request, id):
    post = get_object_or_404(Post, id=id)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post) #PostForm에서 모델을 Post로 지정해주었기 때문에 form은 PostForm의 인스턴스이자 Post의 인스턴스?
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅이 수정되었습니다.')
            return redirect(post) #Post 모델에 get_absolute_url 함수를 정의했으므로 인스턴스를 넣어주기만 해도 url을 추적할 수 있다
    else:                         #따라서 post_detail에 쉽게 접근 가능
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
    })

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}AskDjango's blog{% endblock %}

blog/templates/blog/post_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ post }} 삭제 확인</h1>

    정말 삭제하시겠습니까?

    <form action="" method="POST">
        {% csrf_token %}
        <a href="{{ post.get_absolute_url }}"><button>취소</button></a>
        <input type="submit" value="삭제">
    </form>
</body>
</html>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <p>
                <h2>{{ post.title }}</h2>

                {% if post.photo %}
                    <img src="{{ post.photo.url }}" style="max-width: 100%;">

                    {% thumbnail "100x100" post.photo %}

                    {% thumbnail "100x100" post.photo as thumb %}
                    <img src="{{ thumb.url}}" width="{{ thumb.width }}" height="{{ thumb.height }}">

                    {% thumbnail "100x100" post.photo -- style="" onclick="" class="" %}
                {% endif %}

                {{ post.content|linebreaks }}

                <hr/>

                <h3>Comments</h3>

                <ul>
                    {% for comment in post.comment_set.all %}
                        <li>
                            {{ comment.message }}
                            <small>by {{ comment.author }}</small>
                            <small>at {{ comment.updated_at }}</small>
                        </li>
                    {% endfor %}
                </ul>

                <hr>
                <a href="{% url "blog:post_list" %}" class="btn btn-primary">글목록</a>
                <a href="{% url "blog:post_edit" post.id %}" class="btn btn-secondary">수정</a>
                </p>
            </div>
        </div>
    </div>

{% endblock %}

blog/templates/blog/post_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit">
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                    <div class="jumbotron mt-3">
                        <h1 class="display-4">Django Template <sup>by AskDjango</sup></h1>
                        <p class="lead">여러분의 파이썬/장고 페이스 메이커가 되어 드리겠습니다.</p>
                        <a class="btn btn-primary btn-lg" href="#" role="button">AskDjango 페이스북 그룹 &raquo;</a>
                    </div>
                <div class="alert alert-secondary" role="alert">
                    A simple primary alert—check it out!
                </div>
                <div class="search_bar d-flex justify-content-between mb-3">
                    <form action="" method="get">
                        <input type="text" name="q" value="{{ q }}"/>
                        <input type="submit" value="검색" class="btn btn-primary"/>
                    </form>
                    <a href="{% url "blog:post_new" %}" class="btn btn-primary">New Post</a>
                </div>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>author</th>
                            <th>updated_at</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for post in post_list %}
                        <tr>
                            <td>{{ post.id }}</td>
                            <td><a href="{% url "blog:post_detail" post.id %}">
                                {{ post.title }}</a></td>
                            <td>
                                <small>by{{ post.author }}</small>
                            </td>
                            <td>
                                <small>at {{ post.updated_at }}</small>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}